import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const tokenRoot = path.join(process.cwd(), "src", "tokens");
const outputFile = path.join(tokenRoot, "generated", "tokens.css");
const groups = ["primitive", "semantic", "component"];

const toKebab = (segment) => segment.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
const variableName = (segments) => `--${segments.map(toKebab).join("-")}`;

function flatten(node, segments = [], inheritedType) {
  if (node && typeof node === "object" && "$value" in node) {
    return [{ path: segments, type: node.$type ?? inheritedType, value: node.$value }];
  }
  if (!node || typeof node !== "object" || Array.isArray(node)) return [];
  const nextType = node.$type ?? inheritedType;
  return Object.entries(node)
    .filter(([key]) => !key.startsWith("$"))
    .flatMap(([key, value]) => flatten(value, [...segments, key], nextType));
}

function cssValue(token) {
  const value = token.value;
  if (token.type === "fontFamily" && Array.isArray(value)) {
    return value.map((family) => family.includes(" ") ? `"${family}"` : family).join(", ");
  }
  if (token.type === "shadow" && value && typeof value === "object") {
    return `${value.offsetX} ${value.offsetY} ${value.blur} ${value.spread} ${value.color}`;
  }
  if (typeof value === "string") {
    return value.replace(/\{([^}]+)\}/g, (_match, reference) => `var(${variableName(reference.split("."))})`);
  }
  return String(value);
}

const tokens = groups.flatMap((group) => {
  const directory = path.join(tokenRoot, group);
  return readdirSync(directory)
    .filter((file) => file.endsWith(".tokens.json"))
    .sort()
    .flatMap((file) => flatten(JSON.parse(readFileSync(path.join(directory, file), "utf8"))));
});

const generated = [
  "/* Generated by scripts/generate-tokens.mjs. Edit DTCG JSON sources, not this file. */",
  "@layer tokens {",
  "  :root {",
  ...tokens.map((token) => `    ${variableName(token.path)}: ${cssValue(token)};`),
  "  }",
  "}",
  ""
].join("\n");

if (process.argv.includes("--check")) {
  const current = readFileSync(outputFile, "utf8");
  if (current !== generated) {
    console.error("Generated tokens are stale. Run npm run generate:tokens.");
    process.exitCode = 1;
  }
} else {
  writeFileSync(outputFile, generated);
  console.log(`Generated ${tokens.length} CSS custom properties.`);
}
